name: build
on: push
jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
      - name : Fetch
        id: dotenv
        uses: falti/dotenv-action@v0.2.5
        with:
          path: Test.env
      - name : Print 
        run: echo "${{ steps.dotenv.outputs.name }}"
      - name : Print2
        run: echo "${{ steps.dotenv.outputs.age }}"

