name: build
on: push
jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name : cLONE
        uses: actions/checkout@v2
      - name : Fetch
        id: dotenv
        uses: ./.github/actions/dotenv-action
      - name : Print 
        run: echo "${{ steps.dotenv.outputs.name }}"
      - name : Print2
        run: echo "${{ steps.dotenv.outputs.age }}"

